name: 'Suggest Labels'
description: 'Suggests labels for open issues using AI.'
branding:
  icon: tag
  color: purple
inputs:
  repo:
    description: "The repo with the issues that need label suggestions."
    required: true
  owner:
    description: "The repo owner's user ID."
    required: true
  token:
    description: "Access token that can access the issues on the repo."
    required: false
    default: '${{ github.token }}'
  api_key:
    description: "OpenAI API access key."
    required: true
  email:
    description: "The email address to send the results to."
    required: false
runs:
  using: 'node16'
  main: 'index.js'