name: 'Label Suggestions'
description: 'Suggests labels for open issues using AI.'
inputs:
  repo:
    description: "The repo with the issues that need label suggestions."
    required: true
  owner:
    description: "The repo owner's user ID."
    required: true
  token:
    description: "Access token that can access the issues on the repo."
    required: false
    default: '${{ github.token }}'
  api_key:
    description: "OpenAI API access key."
    required: true
  email:
    description: "The email address to send the results to."
    required: false

outputs:
  issues: # id of output
    description: 'The issue numbers that the action suggests labels for'
  labels: # id of output
    description: 'The suggested labels for the issues outputted in the same order'
runs:
  using: 'node16'
  main: 'index.js'