name: Suggest Labels
on:
  workflow_dispatch:
    inputs:
      readonly:
        description: "readonly: Specify true or 1 to prevent changes from being commited to GitHub"
        default: false
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: snehara99/label-suggestions@0.0.2
      with:
        repo: 'vscode-cmake-tools'
        owner: 'microsoft'
        token: ${{ secrets.GITHUB_TOKEN }} 
        api_key: '9ddc7f61876645d8a981192e5e72309c'
        endpoint: 'https://americasopenai.azure-api.net'
        deployment-id: 'gpt-35-turbo-16k'

